disabled_rules: 
  - colon
  - comma
  - control_statement
  - identifier_name
  - force_cast

line_length: 200

identifier_name:
allowed_symbols: '_'
min_length: 1
max_length: 50
warning: 1
error: 1000
excluded:
- id
